/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class FModePlayer */

#ifndef _Included_FModePlayer
#define _Included_FModePlayer
#ifdef __cplusplus
extern "C" {
#endif
#undef FModePlayer_MODE_NORMAL
#define FModePlayer_MODE_NORMAL 0L
#undef FModePlayer_MODE_LUOLI
#define FModePlayer_MODE_LUOLI 1L
#undef FModePlayer_MODE_DASHU
#define FModePlayer_MODE_DASHU 2L
#undef FModePlayer_MODE_KONGLING
#define FModePlayer_MODE_KONGLING 3L
#undef FModePlayer_MODE_GAOGUI
#define FModePlayer_MODE_GAOGUI 4L
#undef FModePlayer_MODE_JINGXIONG
#define FModePlayer_MODE_JINGXIONG 5L
/*
 * Class:     FModePlayer
 * Method:    play
 * Signature: (Ljava/lang/String;I)V
 */
JNIEXPORT void JNICALL Java_com_packcheng_fmode_FModePlayer_play
        (JNIEnv *, jobject, jstring, jint);

#ifdef __cplusplus
}
#endif
#endif
